-- plugins/init.lua
require('aditya.plugins.colors')
require('aditya.plugins.neotree')
require('aditya.plugins.telescope')
require('aditya.plugins.text-to-colorscheme')
require('aditya.plugins.treesitter')
require('aditya.plugins.toggleterm')
require('aditya.plugins.undotree')
require('aditya.plugins.lazygit')
require('aditya.plugins.harpoon')
