-- plugins/init.lua
require('aditya.plugins.neotree')
require('aditya.plugins.telescope')
require('aditya.plugins.text-to-colorscheme')
require('aditya.plugins.treesitter')
require('aditya.plugins.toggleterm')
require('aditya.plugins.undotree')
require('aditya.plugins.lazygit')
require('aditya.plugins.harpoon')
require('aditya.plugins.session')
require('aditya.plugins.indent-blankline')
require('aditya.plugins.tokyonight')
require('aditya.plugins.catppuccin')
require('aditya.plugins.mason')
require('aditya.plugins.vimtex')
require('aditya.plugins.markdown')
